/* Generated by emx-regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>



/* regex:    "cat|dog|fish"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint16_t)
 */
bool regex_match(const char *input, size_t len) {
    uint16_t state = 0x0092u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint16_t next = 0;
        if (state & 0x0002u) next |= ((uint8_t)(b == 'c') << 2u);
        if (state & 0x0004u) next |= ((uint8_t)(b == 'a') << 3u);
        if (state & 0x0008u) next |= ((uint8_t)(b == 't') << 0u);
        if (state & 0x0010u) next |= ((uint8_t)(b == 'd') << 5u);
        if (state & 0x0020u) next |= ((uint8_t)(b == 'o') << 6u);
        if (state & 0x0040u) next |= ((uint8_t)(b == 'g') << 0u);
        if (state & 0x0080u) next |= ((uint16_t)(b == 'f') << 8u);
        if (state & 0x0100u) next |= ((uint16_t)(b == 'i') << 9u);
        if (state & 0x0200u) next |= ((uint16_t)(b == 's') << 10u);
        if (state & 0x0400u) next |= ((uint8_t)(b == 'h') << 0u);
        state = next;
    }
    return (state & 0x0001u) != 0;
}
