/* Generated by emx-regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>



/* regex:    "abcdefghijklmnopq"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint32_t)
 */
bool regex_match(const char *input, size_t len) {
    uint32_t state = 0x00000001u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint32_t next = 0;
        if (state & 0x00000001u) next |= ((uint8_t)(b == 'a') << 1u);
        if (state & 0x00000002u) next |= ((uint8_t)(b == 'b') << 2u);
        if (state & 0x00000004u) next |= ((uint8_t)(b == 'c') << 3u);
        if (state & 0x00000008u) next |= ((uint8_t)(b == 'd') << 4u);
        if (state & 0x00000010u) next |= ((uint8_t)(b == 'e') << 5u);
        if (state & 0x00000020u) next |= ((uint8_t)(b == 'f') << 6u);
        if (state & 0x00000040u) next |= ((uint8_t)(b == 'g') << 7u);
        if (state & 0x00000080u) next |= ((uint16_t)(b == 'h') << 8u);
        if (state & 0x00000100u) next |= ((uint16_t)(b == 'i') << 9u);
        if (state & 0x00000200u) next |= ((uint16_t)(b == 'j') << 10u);
        if (state & 0x00000400u) next |= ((uint16_t)(b == 'k') << 11u);
        if (state & 0x00000800u) next |= ((uint16_t)(b == 'l') << 12u);
        if (state & 0x00001000u) next |= ((uint16_t)(b == 'm') << 13u);
        if (state & 0x00002000u) next |= ((uint16_t)(b == 'n') << 14u);
        if (state & 0x00004000u) next |= ((uint16_t)(b == 'o') << 15u);
        if (state & 0x00008000u) next |= ((uint32_t)(b == 'p') << 16u);
        if (state & 0x00010000u) next |= ((uint32_t)(b == 'q') << 17u);
        state = next;
    }
    return (state & 0x00020000u) != 0;
}
