/* Generated by emx-regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>



/* regex:    "abcdefghijklmnopqrstuvwxyz012345"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint32_t[2])
 */
bool regex_match(const char *input, size_t len) {
    uint32_t s0 = 0x00000001u;
    uint32_t s1 = 0x00000000u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint32_t n0 = 0;
        uint32_t n1 = 0;
        if (s0 & 0x00000001u) { n0 |= ((uint32_t)(b == 'a') << 1u); }
        if (s0 & 0x00000002u) { n0 |= ((uint32_t)(b == 'b') << 2u); }
        if (s0 & 0x00000004u) { n0 |= ((uint32_t)(b == 'c') << 3u); }
        if (s0 & 0x00000008u) { n0 |= ((uint32_t)(b == 'd') << 4u); }
        if (s0 & 0x00000010u) { n0 |= ((uint32_t)(b == 'e') << 5u); }
        if (s0 & 0x00000020u) { n0 |= ((uint32_t)(b == 'f') << 6u); }
        if (s0 & 0x00000040u) { n0 |= ((uint32_t)(b == 'g') << 7u); }
        if (s0 & 0x00000080u) { n0 |= ((uint32_t)(b == 'h') << 8u); }
        if (s0 & 0x00000100u) { n0 |= ((uint32_t)(b == 'i') << 9u); }
        if (s0 & 0x00000200u) { n0 |= ((uint32_t)(b == 'j') << 10u); }
        if (s0 & 0x00000400u) { n0 |= ((uint32_t)(b == 'k') << 11u); }
        if (s0 & 0x00000800u) { n0 |= ((uint32_t)(b == 'l') << 12u); }
        if (s0 & 0x00001000u) { n0 |= ((uint32_t)(b == 'm') << 13u); }
        if (s0 & 0x00002000u) { n0 |= ((uint32_t)(b == 'n') << 14u); }
        if (s0 & 0x00004000u) { n0 |= ((uint32_t)(b == 'o') << 15u); }
        if (s0 & 0x00008000u) { n0 |= ((uint32_t)(b == 'p') << 16u); }
        if (s0 & 0x00010000u) { n0 |= ((uint32_t)(b == 'q') << 17u); }
        if (s0 & 0x00020000u) { n0 |= ((uint32_t)(b == 'r') << 18u); }
        if (s0 & 0x00040000u) { n0 |= ((uint32_t)(b == 's') << 19u); }
        if (s0 & 0x00080000u) { n0 |= ((uint32_t)(b == 't') << 20u); }
        if (s0 & 0x00100000u) { n0 |= ((uint32_t)(b == 'u') << 21u); }
        if (s0 & 0x00200000u) { n0 |= ((uint32_t)(b == 'v') << 22u); }
        if (s0 & 0x00400000u) { n0 |= ((uint32_t)(b == 'w') << 23u); }
        if (s0 & 0x00800000u) { n0 |= ((uint32_t)(b == 'x') << 24u); }
        if (s0 & 0x01000000u) { n0 |= ((uint32_t)(b == 'y') << 25u); }
        if (s0 & 0x02000000u) { n0 |= ((uint32_t)(b == 'z') << 26u); }
        if (s0 & 0x04000000u) { n0 |= ((uint32_t)(b == '0') << 27u); }
        if (s0 & 0x08000000u) { n0 |= ((uint32_t)(b == '1') << 28u); }
        if (s0 & 0x10000000u) { n0 |= ((uint32_t)(b == '2') << 29u); }
        if (s0 & 0x20000000u) { n0 |= ((uint32_t)(b == '3') << 30u); }
        if (s0 & 0x40000000u) { n0 |= ((uint32_t)(b == '4') << 31u); }
        if (s0 & 0x80000000u) { n1 |= ((uint32_t)(b == '5') << 0u); }
        s0 = n0;
        s1 = n1;
    }
    return ((s1 & 0x00000001u)) != 0;
}
