/* Generated by emx-regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint8_t regex_transitions[14][256] = {
    /* state 0 */ { 0 },
    /* state 1 */ { [' '] = 11 },
    /* state 2 */ { ['r'] = 12 },
    /* state 3 */ { ['e'] = 2 },
    /* state 4 */ { ['t'] = 3 },
    /* state 5 */ { ['t'] = 4 },
    /* state 6 */ { ['e'] = 5 },
    /* state 7 */ { ['l'] = 6 },
    /* state 8 */ { [' '] = 7 },
    /* state 9 */ { ['#'] = 8 },
    /* state 10 */ { [' '] = 9, ['a'] = 10, ['b'] = 10, ['c'] = 10, ['d'] = 10, ['e'] = 10, ['f'] = 10, ['g'] = 10, ['h'] = 10, ['i'] = 10, ['j'] = 10, ['k'] = 10, ['l'] = 10, ['m'] = 10, ['n'] = 10, ['o'] = 10, ['p'] = 10, ['q'] = 10, ['r'] = 10, ['s'] = 10, ['t'] = 10, ['u'] = 10, ['v'] = 10, ['w'] = 10, ['x'] = 10, ['y'] = 10, ['z'] = 10 },
    /* state 11 */ { ['a'] = 10, ['b'] = 10, ['c'] = 10, ['d'] = 10, ['e'] = 10, ['f'] = 10, ['g'] = 10, ['h'] = 10, ['i'] = 10, ['j'] = 10, ['k'] = 10, ['l'] = 10, ['m'] = 10, ['n'] = 10, ['o'] = 10, ['p'] = 10, ['q'] = 10, ['r'] = 10, ['s'] = 10, ['t'] = 10, ['u'] = 10, ['v'] = 10, ['w'] = 10, ['x'] = 10, ['y'] = 10, ['z'] = 10 },
    /* state 12 */ { ['s'] = 13 },
    /* state 13 */ { 0 },
};

/* regex:                "(?x) [a-z]+ # letters"
 * flags:                "x"
 * encoding:             utf8
 * alphabet-compression: no
 * row-deduplication:    no
 * early-exit:           no
 */
bool regex_match(const char *input, size_t len) {
    uint8_t state = 1;
    for (size_t i = 0; i < len; i++) {
        state = regex_transitions[state][(unsigned char)input[i]];
    }
    return state >= 13;
}
