/* Generated by emx-regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>



/* regex:    "hello"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint8_t)
 */
bool regex_match(const char *input, size_t len) {
    uint8_t state = 0x01u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint8_t next = 0;
        if (state & 0x01u) next |= ((uint8_t)(b == 'h') << 1u);
        if (state & 0x02u) next |= ((uint8_t)(b == 'e') << 2u);
        if (state & 0x04u) next |= ((uint8_t)(b == 'l') << 3u);
        if (state & 0x08u) next |= ((uint8_t)(b == 'l') << 4u);
        if (state & 0x10u) next |= ((uint8_t)(b == 'o') << 5u);
        state = next;
    }
    return (state & 0x20u) != 0;
}
