/* Generated by emx-regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>

static const uint8_t regex_trans_3[256] = { ['o'] = 0x30u };

/* regex:    "colou?r"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint8_t)
 */
bool regex_match(const char *input, size_t len) {
    uint8_t state = 0x01u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint8_t next = 0;
        if (state & 0x01u) next |= ((uint8_t)(b == 'c') << 1u);
        if (state & 0x02u) next |= ((uint8_t)(b == 'o') << 2u);
        if (state & 0x04u) next |= ((uint8_t)(b == 'l') << 3u);
        if (state & 0x08u) next |= regex_trans_3[b];
        if (state & 0x10u) next |= ((uint8_t)(b == 'u') << 5u);
        if (state & 0x20u) next |= ((uint8_t)(b == 'r') << 6u);
        state = next;
    }
    return (state & 0x40u) != 0;
}
