/* Generated by emx-regex-cgen – do not edit. */

#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>



/* regex:    "\bword\b"
 * flags:    ""
 * encoding: utf8
 * engine:   bitnfa (uint8_t)
 */
bool regex_match(const char *input, size_t len) {
    uint8_t state = 0x01u;
    for (size_t i = 0; i < len; i++) {
        unsigned char b = (unsigned char)input[i];
        uint8_t next = 0;
        if (state & 0x01u) next |= ((b == 'w') ? 0x02u : 0u);
        if (state & 0x02u) next |= ((b == 'o') ? 0x04u : 0u);
        if (state & 0x04u) next |= ((b == 'r') ? 0x08u : 0u);
        if (state & 0x08u) next |= ((b == 'd') ? 0x10u : 0u);
        state = next;
    }
    return (state & 0x10u) != 0;
}
